name: playcado
description: "A Jellyfin client for iOS and Android"
publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: ^3.8.0

dependencies:
  sentry_flutter: ^9.8.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  dio: ^5.3.3 
  media_kit: ^1.1.0
  media_kit_video: ^2.0.1 
  media_kit_libs_android_video: ^1.2.4
  media_kit_libs_ios_video: ^1.0.4
  media_kit_libs_macos_video: ^1.1.4
  permission_handler: ^12.0.1
  path_provider: ^2.1.2
  jellyfin_dart:
    git:
      url: https://github.com/JchrisM12/jellyfin-dart.git
      ref: v10.11.4
  flutter_secure_storage: ^10.0.0
  logging: ^1.2.0
  cached_network_image: ^3.4.1
  background_downloader: ^9.4.0
  flutter_chrome_cast: ^1.2.6
  wakelock_plus: ^1.4.0
  audio_session: ^0.2.2
  go_router: ^17.0.0
  google_fonts: ^6.2.1
  flutter_flavorizr: ^2.4.1
  flutter_localizations:
    sdk: flutter
  intl: any
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
 
dev_dependencies:
  sentry_dart_plugin: ^3.2.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.11.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
  
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: playcado
  